import nord from './images/nord.png';
import nordAir from './images/nord-air.png';
import russia from './images/rus.png';
import russiaShrt from './images/rus-shrt.png';
import red from './images/red.png';
import redShrt from './images/red-shrt.png';
import namelessCmp from './images/nameless.png';
import fly from './images/fly.png';

const cardsData = [
  {
    general: {
      airline: [
        {
          id: 1,
          name: russia,
        },
      ],
      isCharter: true,
      price: 7712,
      company: 'Clickavia',
      mark: 'cheapest',
      ticketsRemain: false,
    },
    specSugg: [],
    thingsFree: {
      hands: 5,
      baggage: 12,
      text: '',
    },
    thingsForMoney: {
      showRule: false,
      hands: 5,
      baggage: 'red',
      discount: 136,
    },
    flightForward: {
      type: 'direct',
      departureTime: 5,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 185,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 300,
    },
    flightBack: {
      type: 'direct',
      departureTime: 635,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1030,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 275,
    },
  },
  {
    general: {
      airline: [
        {
          id: 1,
          name: nord,
        },
      ],
      isCharter: false,
      price: 8029,
      company: 'biletik_aero',
      mark: 'fastest',
      ticketsRemain: false,
    },
    specSugg: [],
    thingsFree: {
      hands: 5,
      baggage: 'red',
      text: '',
    },
    thingsForMoney: {
      showRule: false,
      hands: 5,
      baggage: 'red',
      discount: 136,
    },
    flightForward: {
      type: 'direct',
      departureTime: 15,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 190,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 295,
    },
    flightBack: {
      type: 'CDG',
      departureTime: 645,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1035,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 270,
    },
  },
  {
    general: {
      airline: [
        {
          id: 1,
          name: nordAir,
        },
      ],
      isCharter: true,
      price: 8164,
      company: 'Aviakassa',
      mark: 'thebest',
      ticketsRemain: false,
    },
    specSugg: [],
    thingsFree: {
      hands: 5,
      baggage: 'none',
      text: '',
    },
    thingsForMoney: {
      showRule: true,
      hands: 5,
      baggage: 12,
      discount: 136,
    },
    flightForward: {
      type: 'direct',
      departureTime: 15,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 190,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 295,
    },
    flightBack: {
      type: 'direct',
      departureTime: 645,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1035,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 270,
    },
  },
  {
    general: {
      airline: [
        {
          id: 1,
          name: red,
        },
      ],
      isCharter: true,
      price: 8240,
      company: 'biletik_aero',
      mark: 'none',
      ticketsRemain: false,
    },
    specSugg: [
      {
        id: 1,
        name: 'Clickavia',
        price: 8302,
      },
      {
        id: 2,
        name: 'Aviakassa',
        price: 8376,
      },
      {
        id: 3,
        name: 'Aviakassa',
        price: 8376,
      },
      {
        id: 4,
        name: 'Aviakassa',
        price: 8376,
      },
      {
        id: 5,
        name: 'Aviakassa',
        price: 8376,
      },
    ],
    thingsFree: {
      hands: 10,
      baggage: 'none',
      text: 'Нет багажа',
    },
    thingsForMoney: {
      showRule: true,
      hands: 10,
      baggage: 20,
      discount: 267,
    },
    flightForward: {
      type: 'direct',
      departureTime: 420,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 570,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 270,
    },
    flightBack: {
      type: 'direct',
      departureTime: 660,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1030,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 250,
    },
  },
  {
    general: {
      airline: [
        {
          id: 1,
          name: redShrt,
        },
        {
          id: 2,
          name: russiaShrt,
        },
      ],
      isCharter: true,
      price: 9108,
      company: 'Clickavia',
      mark: 'none',
      ticketsRemain: false,
    },
    specSugg: [],
    thingsFree: {
      hands: 10,
      baggage: 15,
      text: '',
    },
    thingsForMoney: {
      showRule: false,
      hands: 5,
      baggage: 12,
      discount: 136,
    },
    flightForward: {
      type: 'direct',
      departureTime: 5,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 185,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 300,
    },
    flightBack: {
      type: 'direct',
      departureTime: 660,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1030,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 250,
    },
  },
  {
    general: {
      airline: [
        {
          id: 1,
          name: fly,
        },
      ],
      isCharter: true,
      price: 9269,
      company: 'Biletix',
      mark: 'none',
      ticketsRemain: 4,
    },
    specSugg: [
      {
        id: 1,
        name: 'Svyaznoy Travel',
        price: 9275,
      },
      {
        id: 2,
        name: 'biletik_aero',
        price: 9587,
      },
      {
        id: 3,
        name: 'Aviakassa',
        price: 8376,
      },
      {
        id: 4,
        name: 'Aviakassa',
        price: 8376,
      },
      {
        id: 5,
        name: 'Aviakassa',
        price: 8376,
      },
    ],
    thingsFree: {
      hands: 'none',
      baggage: 20,
      text: 'Нет багажа',
    },
    thingsForMoney: {
      showRule: false,
      hands: 10,
      baggage: 20,
      discount: 267,
    },
    flightForward: {
      type: 'direct',
      departureTime: 450,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 590,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 260,
    },
    flightBack: {
      type: 'direct',
      departureTime: 680,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1055,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 255,
    },
  },
  {
    general: {
      airline: [
        {
          id: 1,
          name: russiaShrt,
        },
        {
          id: 2,
          name: namelessCmp,
        },
      ],
      isCharter: true,
      price: 9485,
      company: 'Clickavia',
      mark: 'none',
      ticketsRemain: false,
    },
    specSugg: [],
    thingsFree: {
      hands: 'none',
      baggage: 15,
      text: '',
    },
    thingsForMoney: {
      showRule: false,
      hands: 5,
      baggage: 12,
      discount: 136,
    },
    flightForward: {
      type: 'direct',
      departureTime: 5,
      departureCity: 'moscow',
      departureDate: '2-24-2018',
      departureAirport: 'VKO',
      arrivalTime: 185,
      arrivalCity: 'barcelona',
      arrivalDate: '2-24-2018',
      arrivalAirport: 'BCN',
      duration: 300,
    },
    flightBack: {
      type: 'direct',
      departureTime: 680,
      departureCity: 'barcelona',
      departureDate: '3-3-2018',
      departureAirport: 'BCN',
      arrivalTime: 1055,
      arrivalCity: 'moscow',
      arrivalDate: '3-3-2018',
      arrivalAirport: 'SVO',
      duration: 255,
    },
  },
];

export default cardsData;
